version: "3.9"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: materialdb
      POSTGRES_USER: materialuser
      POSTGRES_PASSWORD: materialpass
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5555:5432"

  backend:
    build: ./backend
    environment:
      - DATABASE_URL=postgresql://materialuser:materialpass@db:5432/materialdb
    ports:
      - "8096:8000"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://backend:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
